### PR TITLE
Fixes Dependency Errors when building samples by updating artifact IDs

### PR DESCRIPTION
**Pull request by msftph**
See Issue #111 

The artifact IDs for the spark-listeners and spark-listeners-loganalytics were specific spark and scala version numbers in some locations and were base artifact ids in other places. This caused issues when building the artifacts and then building the samples. 

This pull request makes the artifact ids consistent and fixes a dependency in the sample so that the artifacts are picked up properly from the .m2 directory. 

This pull request also updates the documentation with powershell examples of the windows commands to make it easier for users of powershell. 

@nextdynamic for visibility

### CODE REVIEW

**Comment by hallihan** [comment]
I pulled the variables out of the artifactId in #151 to avoid the following warnings:
```
[WARNING] Some problems were encountered while building the effective model for com.microsoft.pnp:spark-listeners_2.4.3_2.11:jar:1.0.0
[WARNING] 'artifactId' contains an expression but should be a constant. @ com.microsoft.pnp:spark-listeners_${spark.version}_${scala.compat.version}:1.0.0, /spark-monitoring/src/spark-listeners/pom.xml, line 12, column 17
[WARNING]
[WARNING] Some problems were encountered while building the effective model for com.microsoft.pnp:spark-listeners-loganalytics_2.4.3_2.11:jar:1.0.0
[WARNING] 'artifactId' contains an expression but should be a constant. @ com.microsoft.pnp:spark-listeners-loganalytics_${spark.version}_${scala.compat.version}:1.0.0, /spark-monitoring/src/spark-listeners-loganalytics/pom.xml, line 10, column 17
[WARNING]
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING]
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
```
It looks like when I tested the sample job for that PR, it pulled the dependency from my local Maven cache with the old artifact id.  I made a small change to the sample pom in this branch, can you give it a try and see if it works for you? https://github.com/mspnp/spark-monitoring/tree/update-sample-dependency (It built on my machine after clearing the maven cache and rebuilding the library, but it will be a while before I have an opportunity to properly test it).

**Comment by nextdynamic** [comment]
Copied your sample pom and it built the jar.

**Comment by msftph** [comment]
I reverted my changes in my local and applied your updated pom and the sample built for me as well.

**Comment by hallihan** [comment]
Closing, superseded by #154

**Pull request closed without merging**
